/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import model.Barang;

/**
 *
 * @author ASUS
 */
public class LaporanTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form LaporanTransaksi
     */
    public LaporanTransaksi() {
        initComponents();
        initRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lKasir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fTanggal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tBelanja = new javax.swing.JTable();
        bLogout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fTotal = new javax.swing.JTextField();
        lMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lKasir.setText("Kasir :");

        jLabel7.setText("Tanggal");

        fTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTanggalActionPerformed(evt);
            }
        });

        tBelanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah", "Harga Pendapatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tBelanja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tBelanjaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tBelanja);

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Pendapatan");

        fTotal.setEditable(false);
        fTotal.setText("0");
        fTotal.setName(""); // NOI18N
        fTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39)
                                .addComponent(fTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lKasir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLogout))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lKasir)
                    .addComponent(bLogout))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMsg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getTanggal(){
        return fTanggal.getText();
    }
    
    public JButton getbLogout() {
        return bLogout;
    }
    
    public void setKasir(String s){
        lKasir.setText(s);
    }
    
    public void setTotal(int i){
        fTotal.setText(Integer.toString(i));
    }
    
    public void setMsg(String s){
        lMsg.setText(s);
    }
    
    public void addActonListener(ActionListener e){
        bLogout.addActionListener(e);
    }   
    
    public void addTableModelListener(TableModelListener e){
        tBelanja.getModel().addTableModelListener(e);
    }
    
    public int getSelectedRow(){
        return tBelanja.getSelectedRow();
    }
    
    public String getSelectedKode(int row){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        String kode = (String) model.getValueAt(row, 0);
        return kode;
    }
    
    public void reset(){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        model.setRowCount(0);
        initRow();
        
    }
    
    public void setTabel(List<Barang> A){
        reset();
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();

        
        for(int i = 0; i < A.size(); i++){
            String Kode = A.get(i).getKode();
            String Nama = A.get(i).getNama();
            int jml = A.get(i).getJumlah();
            int harga = (A.get(i).getJumlah() * A.get(i).getHarga());
            
            Object[] row = {Kode, Nama, jml, harga};
            
            model.insertRow(i, row);
        }
    }
    
    public int getSelectedJumlah(int row){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        String s;
        int jumlah = 0;
        try{
            s = (String) model.getValueAt(row, 2);
            jumlah = Integer.parseInt(s);
        }catch(Exception e){
            lMsg.setText("Jumlah berupa angka");
            return jumlah;
        }
        return jumlah;
    }
    
    private void initRow(){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        String a = "";
        String b = "";
        String c = "";
        int d = 0;       
        Object[] row = {a,b,c,d};
        model.insertRow(0, row);       
    }
    
    
        
    
    
    private void fTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTanggalActionPerformed

    private void fTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTotalActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        
    }//GEN-LAST:event_bLogoutActionPerformed

    private void tBelanjaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBelanjaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tBelanjaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogout;
    private javax.swing.JTextField fTanggal;
    private javax.swing.JTextField fTotal;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lKasir;
    private javax.swing.JLabel lMsg;
    private javax.swing.JTable tBelanja;
    // End of variables declaration//GEN-END:variables
}
