/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import model.Barang;

/**
 *
 * @author CakBin
 */
public class PembelianUI extends javax.swing.JFrame {

    /**
     * Creates new form PembelianUI
     */
    public PembelianUI() {
        initComponents();
        initRow();
    }

    public JButton getbLogout() {
        return bLogout;
    }

    public JButton getbNavData() {
        return bNavData;
    }

    public JButton getbSubmit() {
        return bSubmit;
    }

    public JTable gettBelanja() {
        return tBelanja;
    }
    
    public String getSelectedKode(int row){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        String kode = (String) model.getValueAt(row, 0);
        return kode;
    }
    
    public int getSelectedJumlah(int row){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        String s;
        int jumlah = 0;
        try{
            s = (String) model.getValueAt(row, 2);
            jumlah = Integer.parseInt(s);
        }catch(Exception e){
            lMsg.setText("Jumlah berupa angka");
            return jumlah;
        }
        return jumlah;
    }
    
    public int getSelectedRow(){
        return tBelanja.getSelectedRow();
    }
    
    public void setKasir(String s){
        lKasir.setText(s);
    }
    
    public void setPembeli(int i){
       lPembeli.setText(Integer.toString(i));
    }
    
    public void setTabel(List<Barang> A){
        reset();
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();

        
        for(int i = 0; i < A.size(); i++){
            String Kode = A.get(i).getKode();
            String Nama = A.get(i).getNama();
            int jml = A.get(i).getJumlah();
            int harga = (A.get(i).getJumlah() * A.get(i).getHarga());
            
            Object[] row = {Kode, Nama, jml, harga};
            
            model.insertRow(i, row);
        }
    }
    
    public void setTotal(int i){
        lTotal.setText(Integer.toString(i));
    }
    
    public void addActonListener(ActionListener e){
        bLogout.addActionListener(e);
        bNavData.addActionListener(e);
        bSubmit.addActionListener(e);
        bDelete.addActionListener(e);
    }
    
    public void addTableModelListener(TableModelListener e){
        tBelanja.getModel().addTableModelListener(e);
    }
    
    public void setMsg(String s){
        lMsg.setText(s);
    }
    
    private void initRow(){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        String a = "";
        String b = "";
        String c = "0";
        int d = 0;       
        Object[] row = {a,b,c,d};
        model.insertRow(0, row);       
    }
    
    public void reset(){
        DefaultTableModel model = (DefaultTableModel) tBelanja.getModel();
        model.setRowCount(0);
        initRow();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tBelanja = new javax.swing.JTable();
        lTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lMsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lKasir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lPembeli = new javax.swing.JLabel();
        bSubmit = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        bNavData = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tBelanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tBelanja);

        lTotal.setEditable(false);
        lTotal.setText("0");

        jLabel1.setText("Total");

        jLabel2.setText("Kasir:");

        jLabel3.setText("Pembeli ke:");

        bSubmit.setText("Submit");

        bLogout.setText("Logout");

        bNavData.setText("Data Penjualan");

        bDelete.setLabel("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPembeli))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lKasir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bNavData))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bLogout)
                                    .addComponent(bDelete))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lMsg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lKasir)
                    .addComponent(bLogout)
                    .addComponent(bNavData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lPembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lMsg)))
                    .addComponent(bDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembelianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembelianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembelianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembelianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembelianUI().setVisible(true);
            }
        });
    }

    public JButton getbDelete() {
        return bDelete;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bNavData;
    private javax.swing.JButton bSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lKasir;
    private javax.swing.JLabel lMsg;
    private javax.swing.JLabel lPembeli;
    private javax.swing.JTextField lTotal;
    private javax.swing.JTable tBelanja;
    // End of variables declaration//GEN-END:variables
}
